name: Build Android 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  common:
    uses: ./.github/workflows/common.yml

  build:
    needs: common
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease
          cp app/build/outputs/apk/release/app-release.apk ${{ github.workspace }}/build/baseball.apk

      - name: Upload Android artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-build
          path: ${{ github.workspace }}/build/baseball.apk
